ci: Future-proof range of tested Python versions (#468)
Signed-off-by: Edgar Ramírez Mondragón <edgarrm358@gmail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,38 +32,44 @@ concurrency:
 env:
   FORCE_COLOR: "1"
   # renovate: datasource=pypi depName=uv
-  UV_VERSION: 0.9.29
+  UV_VERSION: 0.10.6
   # renovate: datasource=pypi depName=tox
   TOX_VERSION: 4.44.0
   # renovate: datasource=pypi depName=tox-uv
   TOX_UV_VERSION: 1.29.0
 
 jobs:
+  build-package:
+    name: Build & verify package
+    runs-on: ubuntu-latest
+    outputs:
+      supported-python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}
+    steps:
+      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          fetch-depth: 0
+          persist-credentials: false
+      - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0
+        id: baipp
+
   test:
     name: Integration
     runs-on: ubuntu-24.04
+    needs: build-package
     strategy:
       fail-fast: false
       max-parallel: 3
       matrix:
-        python-version:
-        - "3.14"
-        - "3.13"
-        - "3.12"
+        python-version: ${{ fromJson(needs.build-package.outputs.supported-python-versions) }}
 
     steps:
     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
-      id: setup-python
-      with:
-        python-version: ${{ matrix.python-version }}
-        allow-prereleases: true
     - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
       with:
+        python-version: ${{ matrix.python-version }}
         version: ${{ env.UV_VERSION }}
     - name: Run tests
       env:
-        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
         TAP_POLARSH_TOKEN: ${{ secrets.TAP_POLARSH_TOKEN }}
         TAP_POLARSH_START_DATE: ${{ secrets.TAP_POLARSH_START_DATE }}
       run: >
@@ -72,7 +78,7 @@ jobs:
         --with tox==${{ env.TOX_VERSION }}
         tox -e ${{ matrix.python-version }} -- --junit-xml=junit.xml
     - uses: mikepenz/action-junit-report@74626db7353a25a20a72816467ebf035f674c5f8 # v6.2.0
-      if: ${{ matrix.python-version == '3.13' && success() || failure() }} #  always run even if the previous step fails
+      if: ${{ matrix.python-version == '3.14' && success() || failure() }} #  always run even if the previous step fails
       with:
         annotate_only: true
         comment: true
@@ -85,14 +91,10 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
-      id: setup-python
     - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
       with:
         version: ${{ env.UV_VERSION }}
-    - env:
-        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
-      run: uv tool install --with tox-uv==${{ env.TOX_UV_VERSION }} --from tox==${{ env.TOX_VERSION }} tox
+    - run: uv tool install --with tox-uv==${{ env.TOX_UV_VERSION }} --from tox==${{ env.TOX_VERSION }} tox
     - name: Static type checking
       run: tox -e typing
     - name: Unused, missing and transitive dependencies
